index:
    path: /
    controller: App\Controller\SecurityController::login

ticket:
    path: /ticket
    controller: App\Controller\TicketController::ticket
admin:
    path: /admin
    controller: App\Controller\SecurityController::admin
register:
    path: /register
    controller: App\Controller\RegistrationController::register
